[package]
name = "rialto-parachain-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "l-sync-all-forks" }

[dependencies]
codec = { package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}
log = { version = "0.4.14", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = '1.0', optional = true, features = ['derive'] }

# Bridge depedencies

bp-rialto-parachain = { path = "../../../primitives/chain-rialto-parachain", default-features = false }

# Substrate Dependencies
## Substrate Primitive Dependencies
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }

## Substrate FRAME Dependencies
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "l-sync-all-forks" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "l-sync-all-forks" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "l-sync-all-forks" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }

## Substrate Pallet Dependencies
pallet-aura = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "l-sync-all-forks" }

# Cumulus Dependencies
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }
cumulus-primitives-utility = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }
parachain-info = { git = "https://github.com/paritytech/cumulus", default-features = false , branch = "l-sync-all-forks" }

# Polkadot Dependencies
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "l-sync-all-forks" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "l-sync-all-forks" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "l-sync-all-forks" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "l-sync-all-forks" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "l-sync-all-forks" }

[features]
default = ['std']
runtime-benchmarks = [
	'sp-runtime/runtime-benchmarks',
	'frame-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system-benchmarking',
	'frame-system/runtime-benchmarks',
	'pallet-balances/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
]
std = [
	"bp-rialto-parachain/std",
	"codec/std",
	"log/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-offchain/std",
	"sp-session/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"sp-inherents/std",
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-randomness-collective-flip/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"pallet-transaction-payment/std",
	"parachain-info/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-timestamp/std",
	"cumulus-primitives-utility/std",
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"pallet-aura/std",
	"sp-consensus-aura/std",
]
